export const INCREMENT = 'INCREMENT'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'

export const CHANGE_CALENDAR_RANGE = 'CHANGE_CALENDAR_RANGE'
export const RESET_CALENDAR_RANGE = 'RESET_CALENDAR_RANGE'
export const CHANGE_CALENDAR_MONTHS = 'CHANGE_CALENDAR_MONTHS'

export const SELECT_ARTICLE = 'SELECT_ARTICLE'
